import { Dela_Gothic_One } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/navbar";

const dela = Dela_Gothic_One({ subsets: ["latin"], weight: ["400"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={dela.className}>
        <NavBar></NavBar>
        {children}
      </body>
    </html>
  );
}
